name: test_ploomber
channels:
  - conda-forge
dependencies:
  - black=23.1.0
  - matplotlib=3.6.3
  - molfeat=0.8.6
  - numpy=1.23.2
  - pandas=1.5.3
  - python=3.10.8
  - scikit-learn=1.2.2
  - seaborn=0.12.2
  - pip
  - pip:
    - imbalanced-learn==0.10.1
    - rdkit==2022.9.4
    - scipy==1.8.1
    - ipywidgets
    - ploomber==0.22.4
    - streamlit==1.24.1
    - mols2grid==1.1.1
