meta:
  import_tasks_from: pipeline.preprocessing.yaml
  extract_upstream: false
  source_loader:
    module: brd_pcm

tasks:
  - source: scripts/prep_train.py
    upstream: [featurize]
    product:
      nb: "{{root}}/htmls/prep_train.html"
      X_train: "{{root}}/data/X_train.parquet"
      y_train: "{{root}}/data/y_train.parquet"
      X_test: "{{root}}/data/X_test.parquet"
      y_test: "{{root}}/data/y_test.parquet"
      imblearn_pipe: "{{root}}/models/imblearn_pipe_template.pkl"

  - source: scripts/cross_validate.py
    upstream: [prep_train]
    product:
      nb: "{{root}}/htmls/cross_validate.html"
      cross_val: "{{root}}/ml_outputs/cross_val_scores.csv"

  - source: scripts/uncal_train.py
    upstream: [prep_train]
    product:
      nb: "{{root}}/htmls/train_uncal.html"
      model: "{{root}}/models/uncal_model.pkl.bz2"
      predictions: "{{root}}/ml_outputs/uncal_test_set_preds.csv"
      lig_feat_names: "{{root}}/models/lig_feat_names.pkl"
      prot_feat_names: "{{root}}/models/prot_feat_names.pkl"

  - source: scripts/cal_train.py
    upstream: [prep_train]
    product:
      nb: "{{root}}/htmls/train_cal.html"
      model: "{{root}}/models/cal_models"
      predictions: "{{root}}/ml_outputs/cal_test_set_preds.csv"
      cv_indices: "{{root}}/models/VA_cv_indices.pkl"

  - source: scripts/analyze_test_set.py
    name: analyze_test_set_uncal
    upstream: [uncal_train]
    product:
      nb: "{{root}}/htmls/analyze_test_set_uncal.html"
      roc_curve: "{{root}}/ml_outputs/uncal_test_plots/roc_curve.png"
      pr_curve: "{{root}}/ml_outputs/uncal_test_plots/pr_curve.png"
      cmat: "{{root}}/ml_outputs/uncal_test_plots/uncal_cmat.png"
      conf_metrics: "{{root}}/ml_outputs/uncal_test_cmetrics.csv"
      cal_curve: "{{root}}/ml_outputs/uncal_test_plots/calibration_curve.png"

  - source: scripts/analyze_test_proteins.py
    name: analyze_test_proteins_uncal
    upstream: [uncal_train]
    product:
      nb: "{{root}}/htmls/analyze_test_proteins_uncal.html"
      indiv_prot_csv: "{{root}}/ml_outputs/uncal_test_by_protein.csv"
      indiv_prot_plot: "{{root}}/ml_outputs/uncal_test_plots/pred_by_proteins_all.png"
    nbconvert_export_kwargs:
      config:
        HTMLExporter:
          preprocessors: [nbconvert.preprocessors.TagRemovePreprocessor]
        TagRemovePreprocessor:
          remove_cell_tags: [dictionary]

  - source: scripts/analyze_test_set.py
    name: analyze_test_set_cal
    upstream: [cal_train]
    product:
      nb: "{{root}}/htmls/analyze_test_set_cal.html"
      roc_curve: "{{root}}/ml_outputs/cal_test_plots/roc_curve.png"
      pr_curve: "{{root}}/ml_outputs/cal_test_plots/pr_curve.png"
      cmat: "{{root}}/ml_outputs/cal_test_plots/cal_cmat.png"
      conf_metrics: "{{root}}/ml_outputs/cal_test_cmetrics.csv"
      cal_curve: "{{root}}/ml_outputs/cal_test_plots/calibration_curve.png"

  - source: scripts/analyze_test_proteins.py
    name: analyze_test_proteins_cal
    upstream: [cal_train]
    product:
      nb: "{{root}}/htmls/analyze_test_proteins_cal.html"
      indiv_prot_csv: "{{root}}/ml_outputs/cal_test_by_protein.csv"
      indiv_prot_plot: "{{root}}/ml_outputs/cal_test_plots/pred_by_proteins_all.png"
    nbconvert_export_kwargs:
      config:
        HTMLExporter:
          preprocessors: [nbconvert.preprocessors.TagRemovePreprocessor]
        TagRemovePreprocessor:
          remove_cell_tags: [dictionary]

  - source: scripts/analyze_misclassified.py
    name: analyze_misclassified
    upstream: [cal_train]
    product:
      nb: "{{root}}/htmls/analyze_cal_misclassified.html"
      data: "{{root}}/ml_outputs/cal_test_set_preds_detailed.csv"
    params:
      X_train_data: "{{root}}/data/X_train.parquet"
